(() => {
  "use strict";

  const SVG_NS = "http://www.w3.org/2000/svg";
  const CANVAS = 1800;
  const PX_PER_METRE = 100;
  const STORAGE_KEY = "drumit-project-v2";

  const equipment = [
    {category:"Drums",type:"kick",name:'18" Kick',size:150,icon:"circle"},{category:"Drums",type:"kick",name:'20" Kick',size:165,icon:"circle"},{category:"Drums",type:"kick",name:'22" Kick',size:180,icon:"circle"},{category:"Drums",type:"kick",name:'24" Kick',size:195,icon:"circle"},
    {category:"Drums",type:"snare",name:'12" Snare',size:90,icon:"circle"},{category:"Drums",type:"snare",name:'14" Snare',size:108,icon:"circle"},{category:"Drums",type:"tom",name:'8" Tom',size:68,icon:"circle"},{category:"Drums",type:"tom",name:'10" Tom',size:80,icon:"circle"},{category:"Drums",type:"tom",name:'12" Tom',size:94,icon:"circle"},{category:"Drums",type:"tom",name:'13" Tom',size:101,icon:"circle"},{category:"Drums",type:"floorTom",name:'14" Floor Tom',size:110,icon:"circle"},{category:"Drums",type:"floorTom",name:'16" Floor Tom',size:126,icon:"circle"},{category:"Drums",type:"floorTom",name:'18" Floor Tom',size:142,icon:"circle"},
    {category:"Cymbals",type:"hihat",name:'13" Hi-Hats',size:96,icon:"cymbal"},{category:"Cymbals",type:"hihat",name:'14" Hi-Hats',size:104,icon:"cymbal"},{category:"Cymbals",type:"hihat",name:'15" Hi-Hats',size:112,icon:"cymbal"},{category:"Cymbals",type:"crash",name:'16" Crash',size:118,icon:"cymbal"},{category:"Cymbals",type:"crash",name:'17" Crash',size:126,icon:"cymbal"},{category:"Cymbals",type:"crash",name:'18" Crash',size:134,icon:"cymbal"},{category:"Cymbals",type:"crash",name:'19" Crash',size:142,icon:"cymbal"},{category:"Cymbals",type:"ride",name:'20" Ride',size:150,icon:"cymbal"},{category:"Cymbals",type:"ride",name:'21" Ride',size:158,icon:"cymbal"},{category:"Cymbals",type:"ride",name:'22" Ride',size:166,icon:"cymbal"},{category:"Cymbals",type:"china",name:'16" China',size:118,icon:"cymbal"},{category:"Cymbals",type:"china",name:'18" China',size:134,icon:"cymbal"},{category:"Cymbals",type:"splash",name:'8" Splash',size:62,icon:"cymbal"},{category:"Cymbals",type:"splash",name:'10" Splash',size:74,icon:"cymbal"},{category:"Cymbals",type:"stack",name:'12" Stack',size:84,icon:"cymbal"},
    {category:"Electronic",type:"multipad",name:"Sample Pad",width:128,height:90,icon:"rect"},{category:"Electronic",type:"triggerPad",name:"Trigger Pad",size:74,icon:"circle"},{category:"Electronic",type:"module",name:"Drum Module",width:105,height:70,icon:"rect"},{category:"Electronic",type:"laptop",name:"Laptop",width:130,height:88,icon:"rect"},{category:"Electronic",type:"interface",name:"Audio Interface",width:105,height:52,icon:"rect"},{category:"Electronic",type:"midi",name:"MIDI Controller",width:130,height:62,icon:"rect"},
    {category:"Hardware",type:"throne",name:"Throne",size:95,icon:"circle"},{category:"Hardware",type:"pedal",name:"Single Pedal",width:42,height:92,icon:"pedal"},{category:"Hardware",type:"doublePedal",name:"Double Pedal",width:104,height:92,icon:"pedal"},{category:"Hardware",type:"stand",name:"Straight Stand",width:55,height:96,icon:"rect"},{category:"Hardware",type:"boom",name:"Boom Stand",width:95,height:78,icon:"rect"},{category:"Hardware",type:"snareStand",name:"Snare Stand",size:72,icon:"rect"},{category:"Hardware",type:"rack",name:"Drum Rack",width:250,height:55,icon:"rect"},{category:"Hardware",type:"table",name:"Side Table",width:105,height:78,icon:"rect"},
    {category:"Stage",type:"mic",name:"Microphone",width:28,height:82,icon:"rect"},{category:"Stage",type:"overhead",name:"Overhead Mic",width:32,height:118,icon:"rect"},{category:"Stage",type:"monitor",name:"Stage Monitor",width:125,height:78,icon:"rect"},{category:"Stage",type:"iem",name:"IEM Rack",width:100,height:62,icon:"rect"},{category:"Stage",type:"stagebox",name:"Stage Box",width:88,height:56,icon:"rect"},{category:"Stage",type:"power",name:"Power Point",size:52,icon:"rect"},
    {category:"Accessories",type:"cowbell",name:"Cowbell",width:60,height:36,icon:"rect"},{category:"Accessories",type:"tambourine",name:"Tambourine",size:56,icon:"circle"},{category:"Accessories",type:"block",name:"Jam Block",width:62,height:32,icon:"rect"},{category:"Accessories",type:"fan",name:"Fan",size:70,icon:"circle"},{category:"Accessories",type:"camera",name:"Camera",width:58,height:42,icon:"rect"},{category:"Accessories",type:"custom",name:"Custom Item",width:90,height:62,icon:"rect"}
  ];

  const els = Object.fromEntries([
    "projectName","libraryContent","librarySearch","libraryPanel","libraryToggle","libraryClose","workspaceViewport","workspaceSvg","stageTransform","stageBackground","stageShadow","gridLayer","riserLayer","stageGuides","objectLayer","floatingTools","propertiesPanel","propertiesContent","propertiesTitle","propertiesSubtitle","selectionReadout","objectCount","zoomReadout","toast","gridToggle","snapToggle","snapSize","stageReadout"
  ].map(id => [id, document.getElementById(id)]));
  els.viewport = els.workspaceViewport; els.svg = els.workspaceSvg;

  const defaultStage = () => ({width:6,depth:4,rotation:0,front:"bottom",unit:"m",surface:"black",showDimensions:true,showCenterline:true,showRiser:true,riserWidth:3,riserDepth:2,riserX:1.5,riserY:.4,riserRotation:0,riserLabel:"DRUM RISER"});
  const state = {objects:[],selectedId:null,stage:defaultStage(),zoom:.8,panX:0,panY:0,cleanView:false,grid:true,snap:false,snapCm:10,history:[],future:[],spaceDown:false,panGesture:null,objectGesture:null,panelMode:"object"};

  const uid = () => `drumit-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const createSvg = (tag,attrs={}) => { const n=document.createElementNS(SVG_NS,tag); Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v))); return n; };
  const getSelected = () => state.objects.find(o=>o.id===state.selectedId)||null;
  const stagePx = () => ({w:state.stage.width*PX_PER_METRE,h:state.stage.depth*PX_PER_METRE});
  const stageOffset = () => { const {w,h}=stagePx(); return {x:(CANVAS-w)/2,y:(CANVAS-h)/2,w,h}; };
  const normalizeAngle = a => ((Number(a)%360)+360)%360;
  const fmt = n => Number(n).toFixed(2).replace(/\.00$/,"").replace(/(\.\d)0$/,"$1");
  const toDisplay = metres => state.stage.unit==="ft" ? metres*3.28084 : metres;
  const fromDisplay = value => state.stage.unit==="ft" ? Number(value)/3.28084 : Number(value);
  const unitLabel = () => state.stage.unit==="ft" ? "ft" : "m";

  function snapshot(){return JSON.stringify({projectName:els.projectName.value,objects:state.objects,stage:state.stage,grid:state.grid,snap:state.snap,snapCm:state.snapCm});}
  function restore(serialized){try{const d=JSON.parse(serialized);state.objects=Array.isArray(d.objects)?d.objects:[];state.stage={...defaultStage(),...(d.stage||{})};state.grid=d.grid!==false;state.snap=!!d.snap;state.snapCm=Number(d.snapCm)||10;els.projectName.value=d.projectName||"My Drum Setup";state.selectedId=null;syncStatusControls();render();}catch(e){console.error(e);toast("Could not restore project");}}
  function pushHistory(before=snapshot()){if(state.history.at(-1)!==before){state.history.push(before);if(state.history.length>100)state.history.shift();}state.future=[];}
  function undo(){if(!state.history.length)return;state.future.push(snapshot());restore(state.history.pop());toast("Undone");}
  function redo(){if(!state.future.length)return;state.history.push(snapshot());restore(state.future.pop());toast("Redone");}
  function toast(msg){els.toast.textContent=msg;els.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove("show"),1400);}

  function renderLibrary(filter=""){
    const q=filter.trim().toLowerCase(); els.libraryContent.innerHTML="";
    [...new Set(equipment.map(i=>i.category))].forEach(category=>{
      const items=equipment.filter(i=>i.category===category&&(!q||i.name.toLowerCase().includes(q)||i.type.toLowerCase().includes(q))); if(!items.length)return;
      const section=document.createElement("section");section.className="library-category";const title=document.createElement("div");title.className="category-title";title.textContent=category;section.appendChild(title);const grid=document.createElement("div");grid.className="library-grid";
      items.forEach(item=>{const card=document.createElement("div");card.className="library-item";card.draggable=true;const icon=document.createElement("div");icon.className=`library-icon ${item.icon}`;const label=document.createElement("span");label.textContent=item.name;card.append(icon,label);card.addEventListener("dragstart",e=>{e.dataTransfer.effectAllowed="copy";e.dataTransfer.setData("text/plain",item.type+"|"+item.name);});card.addEventListener("dblclick",()=>addObject(item));grid.appendChild(card);});section.appendChild(grid);els.libraryContent.appendChild(section);
    });
  }

  function addObject(def,x=null,y=null){const before=snapshot();const {w,h}=stagePx();const obj={id:uid(),type:def.type,category:def.category,name:def.name,x:x??w/2,y:y??h/2,width:def.width||def.size||90,height:def.height||def.size||90,rotation:0,scale:1,locked:false,labelVisible:true,opacity:1};state.objects.push(obj);state.selectedId=obj.id;pushHistory(before);render();return obj;}
  function clampObject(o){const {w,h}=stagePx();o.x=Math.max(-100,Math.min(w+100,o.x));o.y=Math.max(-100,Math.min(h+100,o.y));}
  function snapValue(v){if(!state.snap)return v;const s=Math.max(1,state.snapCm);return Math.round(v/s)*s;}

  function applyStageTransform(){const {x,y,w,h}=stageOffset();els.stageTransform.setAttribute("transform",`translate(${x} ${y}) rotate(${state.stage.rotation} ${w/2} ${h/2})`);}
  function applyViewTransform(){els.svg.style.transform=`translate(${state.panX}px,${state.panY}px) scale(${state.zoom}) translate(${-CANVAS/2}px,${-CANVAS/2}px)`;els.zoomReadout.textContent=`${Math.round(state.zoom*100)}%`;}
  function clientToCanvas(clientX,clientY){const r=els.viewport.getBoundingClientRect();return{x:CANVAS/2+(clientX-r.left-r.width/2-state.panX)/state.zoom,y:CANVAS/2+(clientY-r.top-r.height/2-state.panY)/state.zoom};}
  function clientToStage(clientX,clientY){const p=clientToCanvas(clientX,clientY),s=stageOffset(),cx=s.x+s.w/2,cy=s.y+s.h/2,a=-state.stage.rotation*Math.PI/180,dx=p.x-cx,dy=p.y-cy;const rx=dx*Math.cos(a)-dy*Math.sin(a),ry=dx*Math.sin(a)+dy*Math.cos(a);return{x:rx+s.w/2,y:ry+s.h/2};}

  function drawStage(){
    const {w,h}=stagePx();
    [els.stageBackground,els.stageShadow,els.gridLayer].forEach(n=>{n.setAttribute("width",w);n.setAttribute("height",h)});els.stageShadow.setAttribute("transform","translate(10 12)");
    const surfaces={black:"#1a1e22",wood:"#4a392b",grey:"#343a3f",light:"#d9d9d2"};els.stageBackground.setAttribute("fill",surfaces[state.stage.surface]||surfaces.black);els.gridLayer.setAttribute("opacity",state.grid&&!state.cleanView?.48:0);
    const gridSize=Math.max(5,state.snapCm);document.getElementById("gridPattern").setAttribute("width",gridSize);document.getElementById("gridPattern").setAttribute("height",gridSize);document.querySelector("#gridPattern path").setAttribute("d",`M ${gridSize} 0 L 0 0 0 ${gridSize}`);
    els.riserLayer.innerHTML="";if(state.stage.showRiser){const rx=state.stage.riserX*PX_PER_METRE,ry=state.stage.riserY*PX_PER_METRE,rw=state.stage.riserWidth*PX_PER_METRE,rh=state.stage.riserDepth*PX_PER_METRE;const g=createSvg("g",{transform:`rotate(${state.stage.riserRotation} ${rx+rw/2} ${ry+rh/2})`});g.append(createSvg("rect",{x:rx,y:ry,width:rw,height:rh,rx:4,fill:"#282d31",stroke:"#69747c","stroke-width":2,"stroke-dasharray":"8 5",opacity:.85}));const t=createSvg("text",{x:rx+rw/2,y:ry+rh/2,class:"riser-label","text-anchor":"middle"});t.textContent=state.stage.riserLabel||"DRUM RISER";g.append(t);els.riserLayer.append(g);}
    els.stageGuides.innerHTML="";
    if(state.stage.showCenterline){els.stageGuides.append(createSvg("line",{x1:w/2,y1:15,x2:w/2,y2:h-15,stroke:"#586168","stroke-width":1,"stroke-dasharray":"10 12",opacity:.65}));}
    const front=state.stage.front;let x=w/2,y=h-14,anchor="middle",rot=0;if(front==="top"){y=24;rot=180}else if(front==="left"){x=22;y=h/2;rot=90}else if(front==="right"){x=w-22;y=h/2;rot=-90}const ft=createSvg("text",{x,y,class:"stage-front-label","text-anchor":anchor,transform:`rotate(${rot} ${x} ${y})`});ft.textContent="FRONT OF STAGE";els.stageGuides.append(ft);
    if(state.stage.showDimensions){const label=`${fmt(toDisplay(state.stage.width))} ${unitLabel()} × ${fmt(toDisplay(state.stage.depth))} ${unitLabel()}`;const t=createSvg("text",{x:12,y:20,class:"dimension-label"});t.textContent=label;els.stageGuides.append(t);}
    applyStageTransform();
  }

  function appendCircleDrum(g,o,shell="#68737a"){const r=Math.min(o.width,o.height)/2;g.append(createSvg("circle",{r,fill:shell,stroke:"#24292d","stroke-width":7,filter:"url(#softShadow)"}),createSvg("circle",{r:Math.max(12,r-9),fill:"url(#drumGradient)",stroke:"#aeb5ba","stroke-width":2.5}),createSvg("circle",{r:Math.max(8,r-17),fill:"none",stroke:"#d3d8db","stroke-width":1.2,opacity:.7}));for(let a=0;a<360;a+=60){const rad=a*Math.PI/180;g.append(createSvg("circle",{cx:Math.cos(rad)*(r-7),cy:Math.sin(rad)*(r-7),r:2.5,fill:"#252a2e"}));}}
  function appendCymbal(g,o,special=""){const r=Math.min(o.width,o.height)/2;g.append(createSvg("circle",{r,fill:"url(#cymbalGradient)",stroke:"#71501f","stroke-width":2.5,filter:"url(#softShadow)"}));[.8,.62,.43].forEach(k=>g.append(createSvg("circle",{r:r*k,fill:"none",stroke:"#7e5d27","stroke-width":1,opacity:.35})));if(special==="china")g.append(createSvg("circle",{r:r*.72,fill:"none",stroke:"#ffe89a","stroke-width":5,opacity:.35}));if(special==="stack")g.append(createSvg("circle",{r:r*.76,fill:"none",stroke:"#3f321d","stroke-width":4,opacity:.55}));g.append(createSvg("circle",{r:Math.max(6,r*.11),fill:"#8c6727",stroke:"#5f451c","stroke-width":2}),createSvg("circle",{r:Math.max(2,r*.035),fill:"#1b1d1f"}));}
  function appendRect(g,o,fill="#3f474e",rx=7){g.append(createSvg("rect",{x:-o.width/2,y:-o.height/2,width:o.width,height:o.height,rx,fill,stroke:"#89939a","stroke-width":2.5,filter:"url(#softShadow)"}));}
  function appendArt(g,o){
    if(o.type==="kick"){appendCircleDrum(g,o,"#30373c");g.append(createSvg("circle",{r:Math.min(o.width,o.height)*.17,fill:"#353a3f",opacity:.85}));}
    else if(o.type==="snare")appendCircleDrum(g,o,"#9aa4aa");else if(o.type==="tom")appendCircleDrum(g,o,"#68737a");else if(o.type==="floorTom")appendCircleDrum(g,o,"#505b62");
    else if(["crash","ride","splash","hihat","china","stack"].includes(o.type)){appendCymbal(g,o,o.type);if(o.type==="hihat")g.append(createSvg("circle",{r:Math.min(o.width,o.height)*.43,fill:"none",stroke:"#4f3917","stroke-width":2,opacity:.5}));}
    else if(o.type==="throne"){const r=Math.min(o.width,o.height)/2;g.append(createSvg("circle",{r,fill:"#25282b",stroke:"#0c0e10","stroke-width":5,filter:"url(#softShadow)"}),createSvg("circle",{r:r*.75,fill:"#32363a",stroke:"#4a5055","stroke-width":1.5}));}
    else if(["pedal","doublePedal"].includes(o.type)){appendRect(g,o,"url(#hardwareGradient)",5);const count=o.type==="doublePedal"?2:1;for(let i=0;i<count;i++){const cx=count===1?0:(i?o.width*.23:-o.width*.23);g.append(createSvg("rect",{x:cx-12,y:-o.height*.34,width:24,height:o.height*.62,rx:5,fill:"#343b40",stroke:"#c4cbd0","stroke-width":1.5}),createSvg("line",{x1:cx,y1:-o.height*.35,x2:cx,y2:-o.height*.52,stroke:"#c5cbd0","stroke-width":3}));}}
    else if(o.type==="multipad"){appendRect(g,o,"#24292e");for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)g.append(createSvg("rect",{x:x*34-14,y:y*25-10,width:28,height:20,rx:3,fill:"#505a61",stroke:"#79838a","stroke-width":1}));}
    else if(o.type==="laptop"){appendRect(g,o,"#30363b");g.append(createSvg("rect",{x:-o.width*.4,y:-o.height*.38,width:o.width*.8,height:o.height*.55,rx:3,fill:"#10161b",stroke:"#6c767d","stroke-width":2}));}
    else if(o.type==="monitor"){appendRect(g,o,"#292d31");g.append(createSvg("path",{d:`M ${-o.width*.4} ${o.height*.28} L ${-o.width*.32} ${-o.height*.3} L ${o.width*.32} ${-o.height*.3} L ${o.width*.4} ${o.height*.28} Z`,fill:"#191c1f",stroke:"#656d73","stroke-width":2}));}
    else if(o.type==="stand"||o.type==="boom"||o.type==="snareStand"){g.append(createSvg("circle",{r:8,fill:"#79838a",stroke:"#c8ced2","stroke-width":2}),createSvg("line",{x1:0,y1:0,x2:o.type==="boom"?o.width*.42:0,y2:-o.height*.42,stroke:"#9ca5ab","stroke-width":4}),createSvg("line",{x1:0,y1:0,x2:-o.width*.35,y2:o.height*.35,stroke:"#737d84","stroke-width":3}),createSvg("line",{x1:0,y1:0,x2:o.width*.35,y2:o.height*.35,stroke:"#737d84","stroke-width":3}));}
    else if(o.type==="rack"){appendRect(g,o,"#333a40",4);g.append(createSvg("line",{x1:-o.width*.42,y1:0,x2:o.width*.42,y2:0,stroke:"#b0b8bd","stroke-width":6}));}
    else if(o.type==="mic"||o.type==="overhead"){g.append(createSvg("line",{x1:0,y1:o.height*.42,x2:0,y2:-o.height*.3,stroke:"#8f999f","stroke-width":4}),createSvg("line",{x1:0,y1:-o.height*.3,x2:o.width*.25,y2:-o.height*.43,stroke:"#8f999f","stroke-width":3}),createSvg("ellipse",{cx:o.width*.28,cy:-o.height*.44,rx:9,ry:5,fill:"#23272a",stroke:"#9da5aa","stroke-width":1.5}));}
    else if(["tambourine","fan","triggerPad","power"].includes(o.type)){const r=Math.min(o.width,o.height)/2;g.append(createSvg("circle",{r,fill:o.type==="triggerPad"?"#343b40":"#4a5055",stroke:"#9ea7ad","stroke-width":2.5,filter:"url(#softShadow)"}));}
    else appendRect(g,o,o.category==="Accessories"?"#4a3f31":"#3f474e");
  }

  function renderObjects(){els.objectLayer.innerHTML="";state.objects.forEach((o,index)=>{const g=createSvg("g",{class:`drum-object${o.id===state.selectedId?" selected":""}${o.locked?" locked":""}`,transform:`translate(${o.x} ${o.y}) rotate(${o.rotation}) scale(${o.scale})`,"data-id":o.id,opacity:o.opacity??1});appendArt(g,o);const pad=9;g.append(createSvg("rect",{class:"selection-ring",x:-o.width/2-pad,y:-o.height/2-pad,width:o.width+pad*2,height:o.height+pad*2,rx:7,fill:"none",stroke:"#f0ca63","stroke-width":2,"stroke-dasharray":"6 5","vector-effect":"non-scaling-stroke"}));if(o.labelVisible){const t=createSvg("text",{x:0,y:0,class:`drum-label ${["multipad","laptop","monitor","rack","module","interface","midi","custom"].includes(o.type)?"light":""}`});t.textContent=o.name;g.append(t);}g.addEventListener("pointerdown",e=>startObjectDrag(e,o.id));g.addEventListener("click",e=>{e.stopPropagation();selectObject(o.id)});els.objectLayer.append(g);});}

  function render(){drawStage();renderObjects();applyViewTransform();els.objectCount.textContent=`${state.objects.length} item${state.objects.length===1?"":"s"}`;els.stageReadout.textContent=`${fmt(toDisplay(state.stage.width))} × ${fmt(toDisplay(state.stage.depth))} ${unitLabel()} · ${normalizeAngle(state.stage.rotation)}°`;const sel=getSelected();els.selectionReadout.textContent=sel?`${sel.name} · X ${fmt(sel.x/100)} m · Y ${fmt(sel.y/100)} m · ${normalizeAngle(sel.rotation)}°`:"Nothing selected";els.floatingTools.hidden=!sel||state.cleanView;els.svg.classList.toggle("clean-mode",state.cleanView);if(els.propertiesPanel.classList.contains("open")){state.panelMode==="stage"?renderStageProperties():renderObjectProperties();}}
  function selectObject(id){state.selectedId=id;state.panelMode="object";render();}

  function startObjectDrag(e,id){const o=state.objects.find(x=>x.id===id);if(!o||o.locked||state.cleanView)return;e.stopPropagation();state.selectedId=id;const start=clientToStage(e.clientX,e.clientY);state.objectGesture={id,startX:start.x,startY:start.y,objX:o.x,objY:o.y,before:snapshot()};e.currentTarget.setPointerCapture?.(e.pointerId);render();}
  function moveObjectDrag(e){if(!state.objectGesture)return;const o=state.objects.find(x=>x.id===state.objectGesture.id);if(!o)return;const p=clientToStage(e.clientX,e.clientY);o.x=snapValue(state.objectGesture.objX+p.x-state.objectGesture.startX);o.y=snapValue(state.objectGesture.objY+p.y-state.objectGesture.startY);clampObject(o);render();}
  function endObjectDrag(){if(!state.objectGesture)return;pushHistory(state.objectGesture.before);state.objectGesture=null;}

  function rotateSelected(delta){const o=getSelected();if(!o||o.locked)return;const before=snapshot();o.rotation=normalizeAngle(o.rotation+delta);pushHistory(before);render();}
  function duplicateSelected(){const o=getSelected();if(!o)return;const before=snapshot();const copy={...o,id:uid(),name:o.name,x:o.x+20,y:o.y+20,locked:false};state.objects.push(copy);state.selectedId=copy.id;pushHistory(before);render();toast("Duplicated");}
  function deleteSelected(){const o=getSelected();if(!o)return;const before=snapshot();state.objects=state.objects.filter(x=>x.id!==o.id);state.selectedId=null;pushHistory(before);render();}
  function layerSelected(dir){const i=state.objects.findIndex(o=>o.id===state.selectedId);if(i<0)return;const before=snapshot();const [o]=state.objects.splice(i,1);if(dir==="front")state.objects.push(o);else state.objects.unshift(o);pushHistory(before);render();}
  function toggleLock(){const o=getSelected();if(!o)return;const before=snapshot();o.locked=!o.locked;pushHistory(before);render();toast(o.locked?"Locked":"Unlocked");}

  function openPanel(mode){state.panelMode=mode;els.propertiesPanel.classList.add("open");els.propertiesPanel.setAttribute("aria-hidden","false");mode==="stage"?renderStageProperties():renderObjectProperties();}
  function closePanel(){els.propertiesPanel.classList.remove("open");els.propertiesPanel.setAttribute("aria-hidden","true");}
  function row(label,html){return `<div class="property-row"><label>${label}</label>${html}</div>`;}
  function bindChange(id,fn){const el=document.getElementById(id);if(el)el.addEventListener("change",()=>fn(el));}
  function bindInput(id,fn){const el=document.getElementById(id);if(el)el.addEventListener("input",()=>fn(el));}

  function renderObjectProperties(){const o=getSelected();els.propertiesTitle.textContent="Object Properties";els.propertiesSubtitle.textContent=o?o.name:"Select an item";if(!o){els.propertiesContent.innerHTML='<div class="property-note">Select any drum, cymbal or stage item to edit it precisely.</div>';return;}els.propertiesContent.innerHTML=`
    <div class="property-group"><div class="property-group-title">Identity</div>${row("Name",`<input id="pName" value="${escapeHtml(o.name)}">`)}${row("Category",`<input value="${escapeHtml(o.category)}" disabled>`)}${row("Label",`<input id="pLabel" type="checkbox" ${o.labelVisible?"checked":""}>`)}</div>
    <div class="property-group"><div class="property-group-title">Position</div>${row("X (m)",`<input id="pX" type="number" step="0.01" value="${fmt(o.x/100)}">`)}${row("Y (m)",`<input id="pY" type="number" step="0.01" value="${fmt(o.y/100)}">`)}${row("Rotation",`<input id="pRotation" type="number" step="1" value="${normalizeAngle(o.rotation)}">`)}${row("Scale",`<input id="pScale" type="number" min="0.2" max="4" step="0.05" value="${o.scale}">`)}</div>
    <div class="property-group"><div class="property-group-title">Dimensions</div>${row("Width (cm)",`<input id="pWidth" type="number" min="10" max="500" step="1" value="${fmt(o.width)}">`)}${row("Height (cm)",`<input id="pHeight" type="number" min="10" max="500" step="1" value="${fmt(o.height)}">`)}${row("Opacity",`<input id="pOpacity" type="number" min="0.15" max="1" step="0.05" value="${o.opacity??1}">`)}${row("Locked",`<input id="pLocked" type="checkbox" ${o.locked?"checked":""}>`)}</div>
    <div class="property-actions"><button id="pRot90">Rotate +90°</button><button id="pRotReset">Reset rotation</button><button id="pFront">Bring to front</button><button id="pBack">Send to back</button><button id="pDuplicate">Duplicate</button><button id="pDelete">Delete</button></div>`;
    const change=(prop,parser=v=>v)=>el=>{const before=snapshot();o[prop]=parser(el.type==="checkbox"?el.checked:el.value);if(prop==="rotation")o[prop]=normalizeAngle(o[prop]);if(prop==="x"||prop==="y")clampObject(o);pushHistory(before);render();};
    bindChange("pName",change("name",String));bindChange("pLabel",change("labelVisible",Boolean));bindChange("pX",change("x",v=>Number(v)*100));bindChange("pY",change("y",v=>Number(v)*100));bindChange("pRotation",change("rotation",Number));bindChange("pScale",change("scale",v=>Math.max(.2,Math.min(4,Number(v)))));bindChange("pWidth",change("width",v=>Math.max(10,Number(v))));bindChange("pHeight",change("height",v=>Math.max(10,Number(v))));bindChange("pOpacity",change("opacity",v=>Math.max(.15,Math.min(1,Number(v)))));bindChange("pLocked",change("locked",Boolean));
    document.getElementById("pRot90").onclick=()=>rotateSelected(90);document.getElementById("pRotReset").onclick=()=>{const before=snapshot();o.rotation=0;pushHistory(before);render();};document.getElementById("pFront").onclick=()=>layerSelected("front");document.getElementById("pBack").onclick=()=>layerSelected("back");document.getElementById("pDuplicate").onclick=duplicateSelected;document.getElementById("pDelete").onclick=deleteSelected;
  }

  function renderStageProperties(){const s=state.stage;els.propertiesTitle.textContent="Stage Setup";els.propertiesSubtitle.textContent="Dimensions, orientation, grid & riser";els.propertiesContent.innerHTML=`
    <div class="property-group"><div class="property-group-title">Stage</div>${row("Units",`<select id="sUnit"><option value="m" ${s.unit==="m"?"selected":""}>Metric (m)</option><option value="ft" ${s.unit==="ft"?"selected":""}>Imperial (ft)</option></select>`)}${row(`Width (${unitLabel()})`,`<input id="sWidth" type="number" min="1" max="${s.unit==="ft"?52:16}" step="0.1" value="${fmt(toDisplay(s.width))}">`)}${row(`Depth (${unitLabel()})`,`<input id="sDepth" type="number" min="1" max="${s.unit==="ft"?52:16}" step="0.1" value="${fmt(toDisplay(s.depth))}">`)}${row("Stage rotation",`<input id="sRotation" type="number" step="1" value="${normalizeAngle(s.rotation)}">`)}${row("Front edge",`<select id="sFront"><option value="bottom" ${s.front==="bottom"?"selected":""}>Bottom</option><option value="top" ${s.front==="top"?"selected":""}>Top</option><option value="left" ${s.front==="left"?"selected":""}>Left</option><option value="right" ${s.front==="right"?"selected":""}>Right</option></select>`)}${row("Surface",`<select id="sSurface"><option value="black" ${s.surface==="black"?"selected":""}>Black stage</option><option value="grey" ${s.surface==="grey"?"selected":""}>Grey stage</option><option value="wood" ${s.surface==="wood"?"selected":""}>Wood</option><option value="light" ${s.surface==="light"?"selected":""}>Light</option></select>`)}${row("Dimensions",`<input id="sDims" type="checkbox" ${s.showDimensions?"checked":""}>`)}${row("Centre line",`<input id="sCentre" type="checkbox" ${s.showCenterline?"checked":""}>`)}</div>
    <div class="property-group"><div class="property-group-title">Grid & Snap</div>${row("Show grid",`<input id="sGrid" type="checkbox" ${state.grid?"checked":""}>`)}${row("Snap",`<input id="sSnap" type="checkbox" ${state.snap?"checked":""}>`)}${row("Grid size",`<select id="sSnapSize"><option value="5" ${state.snapCm==5?"selected":""}>5 cm</option><option value="10" ${state.snapCm==10?"selected":""}>10 cm</option><option value="25" ${state.snapCm==25?"selected":""}>25 cm</option><option value="50" ${state.snapCm==50?"selected":""}>50 cm</option></select>`)}</div>
    <div class="property-group"><div class="property-group-title">Drum Riser</div>${row("Show riser",`<input id="rShow" type="checkbox" ${s.showRiser?"checked":""}>`)}${row("Label",`<input id="rLabel" value="${escapeHtml(s.riserLabel||"")}">`)}${row("Width (m)",`<input id="rWidth" type="number" min="0.5" max="10" step="0.1" value="${s.riserWidth}">`)}${row("Depth (m)",`<input id="rDepth" type="number" min="0.5" max="10" step="0.1" value="${s.riserDepth}">`)}${row("X (m)",`<input id="rX" type="number" step="0.1" value="${s.riserX}">`)}${row("Y (m)",`<input id="rY" type="number" step="0.1" value="${s.riserY}">`)}${row("Rotation",`<input id="rRotation" type="number" step="1" value="${normalizeAngle(s.riserRotation)}">`)}</div>
    <div class="property-actions"><button id="sRotate90">Stage +90°</button><button id="sRotateReset">Reset rotation</button><button id="sPresetSmall">3×2 m stage</button><button id="sPresetClub">6×4 m stage</button><button id="sPresetFestival">12×8 m stage</button><button id="sFit">Fit stage</button></div>
    <div class="section-rule"></div><div class="property-note">Stage rotation changes the whole visual stage orientation while object coordinates remain tied to the physical stage. Stage size changes are measured in real-world units.</div>`;
    const stageChange=(prop,parser=v=>v)=>el=>{const before=snapshot();s[prop]=parser(el.type==="checkbox"?el.checked:el.value);pushHistory(before);syncStatusControls();render();};
    bindChange("sUnit",el=>{const before=snapshot();s.unit=el.value;pushHistory(before);render();});bindChange("sWidth",stageChange("width",v=>Math.max(1,Math.min(16,fromDisplay(v)))));bindChange("sDepth",stageChange("depth",v=>Math.max(1,Math.min(16,fromDisplay(v)))));bindChange("sRotation",stageChange("rotation",v=>normalizeAngle(Number(v))));bindChange("sFront",stageChange("front",String));bindChange("sSurface",stageChange("surface",String));bindChange("sDims",stageChange("showDimensions",Boolean));bindChange("sCentre",stageChange("showCenterline",Boolean));
    bindChange("sGrid",el=>{const before=snapshot();state.grid=el.checked;pushHistory(before);syncStatusControls();render();});bindChange("sSnap",el=>{state.snap=el.checked;syncStatusControls();render();});bindChange("sSnapSize",el=>{state.snapCm=Number(el.value);syncStatusControls();render();});
    bindChange("rShow",stageChange("showRiser",Boolean));bindChange("rLabel",stageChange("riserLabel",String));bindChange("rWidth",stageChange("riserWidth",Number));bindChange("rDepth",stageChange("riserDepth",Number));bindChange("rX",stageChange("riserX",Number));bindChange("rY",stageChange("riserY",Number));bindChange("rRotation",stageChange("riserRotation",v=>normalizeAngle(Number(v))));
    document.getElementById("sRotate90").onclick=()=>{const before=snapshot();s.rotation=normalizeAngle(s.rotation+90);pushHistory(before);render();};document.getElementById("sRotateReset").onclick=()=>{const before=snapshot();s.rotation=0;pushHistory(before);render();};document.getElementById("sPresetSmall").onclick=()=>setStageSize(3,2);document.getElementById("sPresetClub").onclick=()=>setStageSize(6,4);document.getElementById("sPresetFestival").onclick=()=>setStageSize(12,8);document.getElementById("sFit").onclick=fitView;
  }

  function setStageSize(w,h){const before=snapshot(),old=stagePx();state.stage.width=w;state.stage.depth=h;const neu=stagePx();state.objects.forEach(o=>{o.x=o.x/old.w*neu.w;o.y=o.y/old.h*neu.h;clampObject(o)});pushHistory(before);fitView();render();}
  function escapeHtml(v){return String(v).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
  function syncStatusControls(){els.gridToggle.checked=state.grid;els.snapToggle.checked=state.snap;els.snapSize.value=String(state.snapCm);}

  function fitView(){const {w,h}=stagePx();const angle=normalizeAngle(state.stage.rotation)%180;const visualW=angle===90?h:w,visualH=angle===90?w:h;const r=els.viewport.getBoundingClientRect();state.zoom=Math.max(.15,Math.min(2.5,Math.min((r.width-90)/visualW,(r.height-90)/visualH)));state.panX=0;state.panY=0;applyViewTransform();}
  function setZoom(next){state.zoom=Math.max(.15,Math.min(3,next));applyViewTransform();}

  function save(){localStorage.setItem(STORAGE_KEY,snapshot());toast("Project saved in this browser");}
  function load(){const d=localStorage.getItem(STORAGE_KEY);if(!d)return toast("No saved project yet");restore(d);toast("Project loaded");}
  function newProject(){if(state.objects.length&&!confirm("Clear this layout and start a new project?"))return;const before=snapshot();state.objects=[];state.stage=defaultStage();state.selectedId=null;els.projectName.value="My Drum Setup";pushHistory(before);syncStatusControls();fitView();render();}
  function demo(){const before=snapshot();state.stage={...defaultStage(),width:6,depth:4,showRiser:true,riserWidth:3.2,riserDepth:2.2,riserX:1.4,riserY:.35};const defs=name=>equipment.find(i=>i.name===name);const items=[['22" Kick',300,210,0],['14" Snare',235,280,-8],['10" Tom',260,155,-6],['12" Tom',345,155,8],['16" Floor Tom',410,270,5],['14" Hi-Hats',155,235,-8],['17" Crash',145,120,-8],['18" Crash',410,105,9],['21" Ride',475,190,13],['18" China',515,285,15],['10" Splash',315,95,0],["Sample Pad",150,320,-12],["Double Pedal",300,310,0],["Throne",300,365,0],["Overhead Mic",105,170,-20],["Overhead Mic",510,155,20],["Stage Monitor",300,380,0]];state.objects=[];for(const [name,x,y,r] of items){const d=defs(name);if(!d)continue;const o={id:uid(),type:d.type,category:d.category,name:d.name,x,y,width:d.width||d.size,height:d.height||d.size,rotation:r,scale:1,locked:false,labelVisible:true,opacity:1};state.objects.push(o);}state.selectedId=null;els.projectName.value="Hybrid Rock Kit";pushHistory(before);fitView();render();toast("Demo kit loaded");}

  function exportPng(){const was=state.cleanView;state.cleanView=true;render();const clone=els.svg.cloneNode(true);clone.style.transform="none";clone.setAttribute("width",CANVAS);clone.setAttribute("height",CANVAS);const xml=new XMLSerializer().serializeToString(clone);const blob=new Blob([xml],{type:"image/svg+xml;charset=utf-8"});const url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=CANVAS;c.height=CANVAS;const ctx=c.getContext("2d");ctx.fillStyle="#0d1012";ctx.fillRect(0,0,CANVAS,CANVAS);ctx.drawImage(img,0,0);URL.revokeObjectURL(url);const a=document.createElement("a");a.download=`${els.projectName.value.trim().replace(/[^a-z0-9-_]+/gi,"-")||"drumit-layout"}.png`;a.href=c.toDataURL("image/png");a.click();state.cleanView=was;render();toast("PNG exported");};img.onerror=()=>{state.cleanView=was;render();toast("Export failed")};img.src=url;}

  els.viewport.addEventListener("dragover",e=>{e.preventDefault();e.dataTransfer.dropEffect="copy"});els.viewport.addEventListener("drop",e=>{e.preventDefault();const [type,name]=e.dataTransfer.getData("text/plain").split("|");const def=equipment.find(i=>i.type===type&&(!name||i.name===name))||equipment.find(i=>i.type===type);if(!def)return;const p=clientToStage(e.clientX,e.clientY);addObject(def,snapValue(p.x),snapValue(p.y));});
  els.viewport.addEventListener("pointerdown",e=>{if(state.spaceDown||e.button===1){state.panGesture={x:e.clientX,y:e.clientY,panX:state.panX,panY:state.panY};els.viewport.classList.add("panning");e.preventDefault();}else if(e.target===els.svg||e.target===els.stageBackground||e.target===els.gridLayer){state.selectedId=null;render();}});
  window.addEventListener("pointermove",e=>{if(state.panGesture){state.panX=state.panGesture.panX+e.clientX-state.panGesture.x;state.panY=state.panGesture.panY+e.clientY-state.panGesture.y;applyViewTransform();}else moveObjectDrag(e);});window.addEventListener("pointerup",()=>{if(state.panGesture){state.panGesture=null;els.viewport.classList.remove("panning");}endObjectDrag();});
  els.viewport.addEventListener("wheel",e=>{e.preventDefault();setZoom(state.zoom*(e.deltaY>0?.9:1.1));},{passive:false});

  els.librarySearch.addEventListener("input",e=>renderLibrary(e.target.value));els.libraryToggle?.addEventListener("click",()=>els.libraryPanel.classList.toggle("open"));els.libraryClose?.addEventListener("click",()=>els.libraryPanel.classList.remove("open"));document.getElementById("newProjectBtn").onclick=newProject;document.getElementById("demoBtn").onclick=demo;document.getElementById("saveBtn").onclick=save;document.getElementById("loadBtn").onclick=load;document.getElementById("undoBtn").onclick=undo;document.getElementById("redoBtn").onclick=redo;document.getElementById("zoomOutBtn").onclick=()=>setZoom(state.zoom/1.15);document.getElementById("zoomInBtn").onclick=()=>setZoom(state.zoom*1.15);document.getElementById("zoomReadout").onclick=fitView;document.getElementById("fitBtn").onclick=fitView;document.getElementById("stageBtn").onclick=()=>openPanel("stage");document.getElementById("cleanViewBtn").onclick=()=>{state.cleanView=!state.cleanView;closePanel();render();};document.getElementById("exportBtn").onclick=exportPng;document.getElementById("duplicateBtn").onclick=duplicateSelected;document.getElementById("rotateLeftBtn").onclick=()=>rotateSelected(-15);document.getElementById("rotateRightBtn").onclick=()=>rotateSelected(15);document.getElementById("backBtn").onclick=()=>layerSelected("back");document.getElementById("frontBtn").onclick=()=>layerSelected("front");document.getElementById("lockBtn").onclick=toggleLock;document.getElementById("propertiesBtn").onclick=()=>openPanel("object");document.getElementById("deleteBtn").onclick=deleteSelected;document.getElementById("propertiesClose").onclick=closePanel;
  els.gridToggle.addEventListener("change",()=>{const before=snapshot();state.grid=els.gridToggle.checked;pushHistory(before);render();});els.snapToggle.addEventListener("change",()=>{state.snap=els.snapToggle.checked;render();});els.snapSize.addEventListener("change",()=>{state.snapCm=Number(els.snapSize.value);render();});els.projectName.addEventListener("change",()=>save());

  window.addEventListener("keydown",e=>{const tag=document.activeElement?.tagName;if(tag==="INPUT"||tag==="SELECT")return;if(e.code==="Space"){state.spaceDown=true;e.preventDefault();}const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo();return;}if(mod&&e.key.toLowerCase()==="d"){e.preventDefault();duplicateSelected();return;}if(e.key==="Delete"||e.key==="Backspace"){e.preventDefault();deleteSelected();return;}if(e.key.toLowerCase()==="r"){e.preventDefault();rotateSelected(e.shiftKey?-15:15);return;}const o=getSelected();if(o&&["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)){e.preventDefault();if(o.locked)return;const before=snapshot(),step=e.shiftKey?10:1;if(e.key==="ArrowLeft")o.x-=step;if(e.key==="ArrowRight")o.x+=step;if(e.key==="ArrowUp")o.y-=step;if(e.key==="ArrowDown")o.y+=step;clampObject(o);pushHistory(before);render();}});window.addEventListener("keyup",e=>{if(e.code==="Space")state.spaceDown=false;});window.addEventListener("resize",()=>applyViewTransform());

  renderLibrary();syncStatusControls();requestAnimationFrame(()=>{fitView();render();});
})();
